/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexer.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int PARSE_STRING = 2;
  public static final int ESCAPE_SEQUENCE = 4;
  public static final int BLK_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\4\1\1\1\72\1\2\1\1\22\0\1\2\1\30"+
    "\1\71\1\67\1\0\1\20\1\21\1\0\1\31\1\32\1\17\1\16"+
    "\1\41\1\14\1\15\1\5\2\6\10\10\1\24\1\37\1\27\1\25"+
    "\1\26\1\46\1\40\6\7\2\12\1\65\21\12\1\33\1\3\1\34"+
    "\1\11\1\13\1\0\1\43\1\61\1\47\1\50\1\55\1\62\1\12"+
    "\1\66\1\44\2\12\1\51\1\12\1\64\1\63\1\42\1\56\1\45"+
    "\1\52\1\53\1\60\1\57\1\12\1\70\1\12\1\54\1\35\1\22"+
    "\1\36\1\23\6\0\1\72\u1fa2\0\1\72\1\72\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\1\1\4\1\5\2\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\14\5\1\1\1\21\1\22\1\23"+
    "\1\24\1\23\1\25\1\26\1\27\1\30\1\25\1\26"+
    "\1\31\21\0\1\32\1\33\1\0\1\34\1\35\3\5"+
    "\1\36\13\5\1\37\1\5\1\0\1\40\1\41\2\0"+
    "\1\42\1\0\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\0\1\55\1\56\1\0"+
    "\1\57\3\0\1\60\4\5\1\61\1\5\1\62\1\63"+
    "\1\64\1\5\1\65\6\5\1\66\1\67\1\0\1\70"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\5\1\77"+
    "\1\100\1\101\1\102\1\5\1\103\1\104\1\105\1\5"+
    "\1\0\1\106\1\107\3\5\1\0\2\5\1\110\1\111"+
    "\1\112\1\113\1\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\354\0\354"+
    "\0\u02ff\0\354\0\354\0\354\0\354\0\u0213\0\354\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512"+
    "\0\u054d\0\u0588\0\u05c3\0\u05fe\0\354\0\u0639\0\u0674\0\354"+
    "\0\u06af\0\u0639\0\u0639\0\354\0\354\0\354\0\354\0\u06ea"+
    "\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811\0\u084c\0\u0887\0\u08c2"+
    "\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a"+
    "\0\u0213\0\u0213\0\u0289\0\u0ad5\0\354\0\354\0\u0b10\0\u0b4b"+
    "\0\u0b86\0\u01d8\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8"+
    "\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u01d8\0\u0e4a\0\u0e85"+
    "\0\354\0\354\0\u0ec0\0\u0efb\0\354\0\u0f36\0\354\0\354"+
    "\0\354\0\354\0\354\0\354\0\354\0\354\0\354\0\354"+
    "\0\u0f71\0\354\0\354\0\u0fac\0\354\0\u0fe7\0\u1022\0\u105d"+
    "\0\354\0\u1098\0\u10d3\0\u110e\0\u1149\0\u01d8\0\u1184\0\u01d8"+
    "\0\u01d8\0\u01d8\0\u11bf\0\u01d8\0\u11fa\0\u1235\0\u1270\0\u12ab"+
    "\0\u12e6\0\u1321\0\u01d8\0\354\0\u135c\0\u0efb\0\u0f36\0\354"+
    "\0\354\0\354\0\354\0\u1397\0\u13d2\0\u01d8\0\u140d\0\u01d8"+
    "\0\u01d8\0\u1448\0\u01d8\0\u01d8\0\u01d8\0\u1483\0\u14be\0\u01d8"+
    "\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u01d8"+
    "\0\u01d8\0\354\0\u01d8\0\u01d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\5\1\7\1\10\1\11\1\12"+
    "\1\11\1\13\1\12\1\13\1\14\1\15\6\13\1\16"+
    "\3\5\1\13\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\13"+
    "\1\34\1\35\1\36\1\37\1\40\1\12\1\41\5\12"+
    "\1\42\1\43\2\12\1\44\1\12\1\45\1\0\1\46"+
    "\1\47\1\46\1\50\1\51\46\46\1\52\10\46\1\53"+
    "\4\46\1\54\1\46\3\0\1\55\47\0\1\56\10\0"+
    "\1\57\6\0\5\60\1\61\11\60\1\62\53\60\100\0"+
    "\1\63\6\0\1\64\1\0\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\47\0"+
    "\1\100\1\101\1\12\2\101\1\12\2\101\1\0\1\101"+
    "\1\102\4\101\4\0\1\101\7\0\1\101\1\0\4\12"+
    "\1\101\20\12\1\0\1\12\7\0\1\101\1\11\1\12"+
    "\1\11\1\101\1\12\2\101\1\103\6\101\4\0\1\101"+
    "\7\0\1\101\1\0\4\12\1\101\20\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\25\12\1\0\1\12\7\0\2\101\1\12\2\101"+
    "\1\12\2\101\1\0\6\101\4\0\1\101\7\0\1\101"+
    "\1\0\4\12\1\101\20\12\1\0\1\12\7\0\1\101"+
    "\1\11\1\12\1\11\1\101\1\12\2\101\1\0\6\101"+
    "\4\0\1\101\7\0\1\101\1\0\4\12\1\101\20\12"+
    "\1\104\1\12\10\0\1\103\1\0\1\103\116\0\1\105"+
    "\62\0\1\106\53\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\1\12\1\107\1\12\1\110\21\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\22\12\1\111\2\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\20\12\1\112\4\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\13\12"+
    "\1\113\11\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\1\12\1\114\4\12"+
    "\1\115\16\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\13\12\1\116\11\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\2\12\1\117\10\12\1\120\11\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\2\12\1\121\13\12\1\122\6\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\24\12\1\123\1\0\1\12\7\0"+
    "\10\12\1\0\6\12\4\0\1\12\7\0\1\12\1\0"+
    "\7\12\1\124\4\12\1\125\10\12\1\0\1\12\7\0"+
    "\10\12\1\0\6\12\4\0\1\12\7\0\1\12\1\0"+
    "\3\12\1\126\21\12\1\0\1\12\7\0\10\12\1\0"+
    "\6\12\4\0\1\12\7\0\1\12\1\0\21\12\1\127"+
    "\3\12\1\0\1\12\51\0\1\130\3\0\1\131\1\0"+
    "\1\132\2\0\1\133\1\134\1\135\5\0\1\136\2\0"+
    "\1\46\1\0\1\46\2\0\64\46\1\0\1\46\1\0"+
    "\2\47\1\0\1\47\72\0\1\51\66\0\5\60\1\0"+
    "\11\60\1\0\53\60\17\0\1\137\60\0\1\140\66\0"+
    "\2\141\1\0\1\141\67\0\2\142\1\0\1\142\67\0"+
    "\2\143\1\0\1\143\67\0\2\144\1\0\1\144\67\0"+
    "\2\145\1\0\1\145\67\0\2\146\1\0\1\146\67\0"+
    "\2\147\1\0\1\147\67\0\2\150\1\0\1\150\113\0"+
    "\1\151\46\0\2\152\1\0\1\152\67\0\2\153\1\0"+
    "\1\153\20\0\1\154\46\0\2\155\1\0\1\155\20\0"+
    "\1\156\72\0\1\157\45\0\1\160\1\161\3\160\2\100"+
    "\1\162\2\100\1\162\2\100\1\160\6\100\4\160\1\100"+
    "\7\160\1\100\1\160\4\162\1\100\20\162\1\160\1\162"+
    "\2\160\70\0\1\136\7\0\10\12\1\0\6\12\4\0"+
    "\1\12\7\0\1\12\1\0\2\12\1\163\22\12\1\0"+
    "\1\12\7\0\10\12\1\0\6\12\4\0\1\12\7\0"+
    "\1\12\1\0\2\12\1\164\16\12\1\165\3\12\1\0"+
    "\1\12\7\0\10\12\1\0\6\12\4\0\1\12\7\0"+
    "\1\12\1\0\6\12\1\166\16\12\1\0\1\12\7\0"+
    "\10\12\1\0\6\12\4\0\1\12\7\0\1\12\1\0"+
    "\1\12\1\167\23\12\1\0\1\12\7\0\10\12\1\0"+
    "\6\12\4\0\1\12\7\0\1\12\1\0\3\12\1\170"+
    "\21\12\1\0\1\12\7\0\10\12\1\0\6\12\4\0"+
    "\1\12\7\0\1\12\1\0\3\12\1\171\21\12\1\0"+
    "\1\12\7\0\10\12\1\0\6\12\4\0\1\12\7\0"+
    "\1\12\1\0\20\12\1\172\4\12\1\0\1\12\7\0"+
    "\10\12\1\0\6\12\4\0\1\12\7\0\1\12\1\0"+
    "\10\12\1\173\14\12\1\0\1\12\7\0\10\12\1\0"+
    "\6\12\4\0\1\12\7\0\1\12\1\0\11\12\1\174"+
    "\13\12\1\0\1\12\7\0\10\12\1\0\6\12\4\0"+
    "\1\12\7\0\1\12\1\0\12\12\1\175\12\12\1\0"+
    "\1\12\7\0\10\12\1\0\6\12\4\0\1\12\7\0"+
    "\1\12\1\0\17\12\1\176\5\12\1\0\1\12\7\0"+
    "\10\12\1\0\6\12\4\0\1\12\7\0\1\12\1\0"+
    "\13\12\1\177\11\12\1\0\1\12\7\0\10\12\1\0"+
    "\6\12\4\0\1\12\7\0\1\12\1\0\10\12\1\200"+
    "\14\12\1\0\1\12\7\0\10\12\1\0\6\12\4\0"+
    "\1\12\7\0\1\12\1\0\15\12\1\201\1\202\6\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\11\12\1\203\13\12\1\0\1\12"+
    "\11\0\1\204\2\0\2\204\26\0\4\204\1\0\20\204"+
    "\1\0\1\204\10\0\3\205\32\0\1\205\3\0\2\205"+
    "\4\0\1\205\3\0\2\205\16\0\1\206\72\0\3\207"+
    "\32\0\1\207\3\0\2\207\4\0\1\207\3\0\2\207"+
    "\11\0\2\210\1\0\1\210\67\0\2\211\1\0\1\211"+
    "\67\0\2\212\1\0\1\212\67\0\2\213\1\0\1\213"+
    "\66\0\1\160\1\161\72\160\1\161\3\160\10\162\1\160"+
    "\6\162\4\160\1\162\7\160\1\162\1\160\25\162\1\160"+
    "\1\162\2\160\5\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\3\12\1\214\21\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\22\12\1\215\2\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\5\12"+
    "\1\216\17\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\6\12\1\217\16\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\11\12\1\220\13\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\13\12\1\221\11\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\10\12"+
    "\1\222\14\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\22\12\1\223\2\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\13\12\1\224\11\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\4\12\1\225\20\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\1\12"+
    "\1\226\23\12\1\0\1\12\10\0\3\227\32\0\1\227"+
    "\3\0\2\227\4\0\1\227\3\0\2\227\15\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\4\12"+
    "\1\230\20\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\11\12\1\231\13\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\23\12\1\232\1\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\11\12\1\233\13\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\7\12"+
    "\1\234\15\12\1\0\1\12\10\0\3\235\32\0\1\235"+
    "\3\0\2\235\4\0\1\235\3\0\2\235\15\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\7\12"+
    "\1\236\15\12\1\0\1\12\7\0\10\12\1\0\6\12"+
    "\4\0\1\12\7\0\1\12\1\0\22\12\1\237\2\12"+
    "\1\0\1\12\7\0\10\12\1\0\6\12\4\0\1\12"+
    "\7\0\1\12\1\0\3\12\1\240\21\12\1\0\1\12"+
    "\7\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\4\12\1\241\20\12\1\0\1\12\10\0\3\242"+
    "\32\0\1\242\3\0\2\242\4\0\1\242\3\0\2\242"+
    "\15\0\10\12\1\0\6\12\4\0\1\12\7\0\1\12"+
    "\1\0\22\12\1\243\2\12\1\0\1\12\7\0\10\12"+
    "\1\0\6\12\4\0\1\12\7\0\1\12\1\0\11\12"+
    "\1\244\13\12\1\0\1\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5782];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\11\1\2\11\1\1\4\11\1\1\1\11"+
    "\15\1\1\11\2\1\1\11\3\1\4\11\1\1\21\0"+
    "\2\1\1\0\2\11\21\1\1\0\2\11\2\0\1\11"+
    "\1\0\12\11\1\0\2\11\1\0\1\11\3\0\1\11"+
    "\22\1\1\11\1\0\2\1\4\11\13\1\1\0\5\1"+
    "\1\0\4\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer strBuff = new StringBuffer();

	int nestedBlockCommentCount = 0;
	
    public long getChar() {
        return yychar + 1;
    }

    public int getColumn() {
        return yycolumn + 1;
    }

    public int getLine() {
        return yyline + 1;
    }

    public String getText() {
        return yytext();
    }
    
    public double ParseDouble(String s)
    {
        return Double.parseDouble(s);
    }

    // TODO(afb) :: Add negative number parsing
    public int ParseInteger(String s)
    {
        int result = Integer.parseInt(s);
        return result;
    }

    public int ParseBinaryToInteger(String s)
    {
        s = s.substring(2);
        return Integer.parseInt(s, 2);
    }

    public Integer ParseHexToInteger(String s)
    {
		String num = s.replaceFirst("#x", "");
		num = num.replaceAll(" ", "");
		return Integer.parseInt(num, 16);
    }

	public Character ParseUnicodeToChar(String s)
	{
		int c = Integer.parseInt(s.substring(2), 16);
		return Character.valueOf(Character.toChars(c)[0]);
	}
	
    // TODO(afb) :: Consider making it a Character
    public Character ParseChar(String s)
    {
        return s.charAt(2);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext()+">");
            } 
            // fall through
          case 77: break;
          case 2: 
            { yychar = 0;
            } 
            // fall through
          case 78: break;
          case 3: 
            { 
            } 
            // fall through
          case 79: break;
          case 4: 
            { return new Symbol(sym.INT, ParseInteger(yytext()));
            } 
            // fall through
          case 80: break;
          case 5: 
            { return new Symbol(sym.VAR, yytext());
            } 
            // fall through
          case 81: break;
          case 6: 
            { return new Symbol(sym.DOT);
            } 
            // fall through
          case 82: break;
          case 7: 
            { return new Symbol(sym.COLON);
            } 
            // fall through
          case 83: break;
          case 8: 
            { return new Symbol(sym.LPAREN);
            } 
            // fall through
          case 84: break;
          case 9: 
            { return new Symbol(sym.RPAREN);
            } 
            // fall through
          case 85: break;
          case 10: 
            { return new Symbol(sym.LBRACKET);
            } 
            // fall through
          case 86: break;
          case 11: 
            { return new Symbol(sym.RBRACKET);
            } 
            // fall through
          case 87: break;
          case 12: 
            { return new Symbol(sym.LBRACE);
            } 
            // fall through
          case 88: break;
          case 13: 
            { return new Symbol(sym.RBRACE);
            } 
            // fall through
          case 89: break;
          case 14: 
            { return new Symbol(sym.SEMI);
            } 
            // fall through
          case 90: break;
          case 15: 
            { return new Symbol(sym.AT);
            } 
            // fall through
          case 91: break;
          case 16: 
            { return new Symbol(sym.COMMA);
            } 
            // fall through
          case 92: break;
          case 17: 
            { yybegin(PARSE_STRING);
            } 
            // fall through
          case 93: break;
          case 18: 
            { strBuff.append(yytext());
            } 
            // fall through
          case 94: break;
          case 19: 
            { /* User generated line break within a string. Do nothing */
            } 
            // fall through
          case 95: break;
          case 20: 
            { yybegin(ESCAPE_SEQUENCE);
            } 
            // fall through
          case 96: break;
          case 21: 
            { yybegin(PARSE_STRING); strBuff.append("\t");
            } 
            // fall through
          case 97: break;
          case 22: 
            { yybegin(PARSE_STRING); strBuff.append("\n");
            } 
            // fall through
          case 98: break;
          case 23: 
            { yybegin(YYINITIAL);
					Symbol s = new Symbol(sym.STRING, strBuff.toString());
					strBuff = new StringBuffer();
					return s;
            } 
            // fall through
          case 99: break;
          case 24: 
            { yybegin(PARSE_STRING); strBuff.append("\\");
            } 
            // fall through
          case 100: break;
          case 25: 
            { yychar -= yytext().length();
            } 
            // fall through
          case 101: break;
          case 26: 
            { nestedBlockCommentCount += 1;
					yychar -= 2;
					yybegin(BLK_COMMENT);
            } 
            // fall through
          case 102: break;
          case 27: 
            { return new Symbol(sym.DOUBLE, ParseDouble(yytext()));
            } 
            // fall through
          case 103: break;
          case 28: 
            { return new Symbol(sym.RB_COLON);
            } 
            // fall through
          case 104: break;
          case 29: 
            { return new Symbol(sym.LB_COLON);
            } 
            // fall through
          case 105: break;
          case 30: 
            { return new Symbol(sym.IF);
            } 
            // fall through
          case 106: break;
          case 31: 
            { return new Symbol(sym.OR);
            } 
            // fall through
          case 107: break;
          case 32: 
            { return new Symbol(sym.TRUE);
            } 
            // fall through
          case 108: break;
          case 33: 
            { return new Symbol(sym.NIL);
            } 
            // fall through
          case 109: break;
          case 34: 
            { return new Symbol(sym.FALSE);
            } 
            // fall through
          case 110: break;
          case 35: 
            { nestedBlockCommentCount += 1;
			yychar -= 2;
            } 
            // fall through
          case 111: break;
          case 36: 
            { nestedBlockCommentCount -= 1;
			yychar -= 2;
			if (nestedBlockCommentCount == 0){
				yybegin(YYINITIAL);
			}
            } 
            // fall through
          case 112: break;
          case 37: 
            { return new Symbol(sym.DIV);
            } 
            // fall through
          case 113: break;
          case 38: 
            { return new Symbol(sym.MINUS);
            } 
            // fall through
          case 114: break;
          case 39: 
            { return new Symbol(sym.PLUS);
            } 
            // fall through
          case 115: break;
          case 40: 
            { return new Symbol(sym.MUL);
            } 
            // fall through
          case 116: break;
          case 41: 
            { return new Symbol(sym.MOD);
            } 
            // fall through
          case 117: break;
          case 42: 
            { return new Symbol(sym.BIT_AND);
            } 
            // fall through
          case 118: break;
          case 43: 
            { return new Symbol(sym.BIT_OR);
            } 
            // fall through
          case 119: break;
          case 44: 
            { return new Symbol(sym.BIT_NOT);
            } 
            // fall through
          case 120: break;
          case 45: 
            { return new Symbol(sym.EQUAL);
            } 
            // fall through
          case 121: break;
          case 46: 
            { return new Symbol(sym.COND, "GT");
            } 
            // fall through
          case 122: break;
          case 47: 
            { return new Symbol(sym.COND, "LT");
            } 
            // fall through
          case 123: break;
          case 48: 
            { /* Line comment. Do Nothing*/
            } 
            // fall through
          case 124: break;
          case 49: 
            { return new Symbol(sym.AND);
            } 
            // fall through
          case 125: break;
          case 50: 
            { return new Symbol(sym.CAR);
            } 
            // fall through
          case 126: break;
          case 51: 
            { return new Symbol(sym.CDR);
            } 
            // fall through
          case 127: break;
          case 52: 
            { return new Symbol(sym.DEF);
            } 
            // fall through
          case 128: break;
          case 53: 
            { return new Symbol(sym.LET);
            } 
            // fall through
          case 129: break;
          case 54: 
            { return new Symbol(sym.NOT);
            } 
            // fall through
          case 130: break;
          case 55: 
            { return new Symbol(sym.CHAR, ParseChar(yytext()));
            } 
            // fall through
          case 131: break;
          case 56: 
            { return new Symbol(sym.INT, ParseBinaryToInteger(yytext()));
            } 
            // fall through
          case 132: break;
          case 57: 
            { return new Symbol(sym.INT, ParseHexToInteger(yytext()));
            } 
            // fall through
          case 133: break;
          case 58: 
            { return new Symbol(sym.ASSIGN);
            } 
            // fall through
          case 134: break;
          case 59: 
            { return new Symbol(sym.COND, "GE");
            } 
            // fall through
          case 135: break;
          case 60: 
            { return new Symbol(sym.COND, "LE");
            } 
            // fall through
          case 136: break;
          case 61: 
            { return new Symbol(sym.COND, "NE");
            } 
            // fall through
          case 137: break;
          case 62: 
            { return new Symbol(sym.PAIR);
            } 
            // fall through
          case 138: break;
          case 63: 
            { return new Symbol(sym.PROC);
            } 
            // fall through
          case 139: break;
          case 64: 
            { return new Symbol(sym.READ);
            } 
            // fall through
          case 140: break;
          case 65: 
            { return new Symbol(sym.LIST);
            } 
            // fall through
          case 141: break;
          case 66: 
            { return new Symbol(sym.SIZE);
            } 
            // fall through
          case 142: break;
          case 67: 
            { return new Symbol(sym.THEN);
            } 
            // fall through
          case 143: break;
          case 68: 
            { return new Symbol(sym.ELSE);
            } 
            // fall through
          case 144: break;
          case 69: 
            { return new Symbol(sym.EQV);
            } 
            // fall through
          case 145: break;
          case 70: 
            { return new Symbol(sym.IS_PAIR);
            } 
            // fall through
          case 146: break;
          case 71: 
            { return new Symbol(sym.PRINT);
            } 
            // fall through
          case 147: break;
          case 72: 
            { return new Symbol(sym.SUBSTR);
            } 
            // fall through
          case 148: break;
          case 73: 
            { return new Symbol(sym.EQL);
            } 
            // fall through
          case 149: break;
          case 74: 
            { return new Symbol(sym.CHAR, ParseUnicodeToChar(yytext()));
            } 
            // fall through
          case 150: break;
          case 75: 
            { return new Symbol(sym.PRINTLN);
            } 
            // fall through
          case 151: break;
          case 76: 
            { return new Symbol(sym.READINT);
            } 
            // fall through
          case 152: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
