
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 11;
  public static final int LT = 13;
  public static final int NE = 16;
  public static final int PLUS = 7;
  public static final int INT = 17;
  public static final int RBRACE = 6;
  public static final int RPAREN = 4;
  public static final int CHAR = 2;
  public static final int LPAREN = 3;
  public static final int GT = 12;
  public static final int LBRACE = 5;
  public static final int LE = 15;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int GE = 14;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int BOOL = 18;
  public static final int MUL = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CHAR",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "GT",
  "LT",
  "GE",
  "LE",
  "NE",
  "INT",
  "BOOL"
  };
}

