
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 6;
  public static final int CHAR = 48;
  public static final int GE = 39;
  public static final int BIT_NOT = 34;
  public static final int BIT_AND = 32;
  public static final int CAR = 12;
  public static final int DOUBLE = 47;
  public static final int SEMI = 35;
  public static final int CDR = 13;
  public static final int LPAREN = 2;
  public static final int INT = 46;
  public static final int PRINTLN = 23;
  public static final int MINUS = 25;
  public static final int RPAREN = 3;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int LT = 38;
  public static final int RB_COLON = 9;
  public static final int NIL = 21;
  public static final int OR = 30;
  public static final int COMMA = 44;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int ASSIGN = 42;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int EQUAL = 43;
  public static final int RBRACKET = 7;
  public static final int TRUE = 49;
  public static final int SIZE = 15;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int MOD = 28;
  public static final int PAIR = 11;
  public static final int IS_PAIR = 10;
  public static final int EQV = 16;
  public static final int LBRACE = 4;
  public static final int LIST = 14;
  public static final int EQL = 17;
  public static final int SUBSTR = 18;
  public static final int RBRACE = 5;
  public static final int NE = 41;
  public static final int LB_COLON = 8;
  public static final int PROC = 20;
  public static final int DEF = 19;
  public static final int AT = 36;
  public static final int BIT_OR = 33;
  public static final int FALSE = 50;
  public static final int GT = 37;
  public static final int VAR = 45;
  public static final int PRINT = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LB_COLON",
  "RB_COLON",
  "IS_PAIR",
  "PAIR",
  "CAR",
  "CDR",
  "LIST",
  "SIZE",
  "EQV",
  "EQL",
  "SUBSTR",
  "DEF",
  "PROC",
  "NIL",
  "PRINT",
  "PRINTLN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "BIT_AND",
  "BIT_OR",
  "BIT_NOT",
  "SEMI",
  "AT",
  "GT",
  "LT",
  "GE",
  "LE",
  "NE",
  "ASSIGN",
  "EQUAL",
  "COMMA",
  "VAR",
  "INT",
  "DOUBLE",
  "CHAR",
  "TRUE",
  "FALSE"
  };
}

