
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 7;
  public static final int CHAR = 53;
  public static final int READINT = 27;
  public static final int BIT_NOT = 39;
  public static final int BIT_AND = 37;
  public static final int CASE = 23;
  public static final int CAR = 13;
  public static final int DOUBLE = 52;
  public static final int COND = 42;
  public static final int SEMI = 40;
  public static final int CDR = 14;
  public static final int LPAREN = 3;
  public static final int INT = 51;
  public static final int PRINTLN = 25;
  public static final int MINUS = 30;
  public static final int RPAREN = 4;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int RB_COLON = 10;
  public static final int NIL = 22;
  public static final int OR = 35;
  public static final int COMMA = 45;
  public static final int DIV = 32;
  public static final int PLUS = 29;
  public static final int IF = 46;
  public static final int ASSIGN = 43;
  public static final int EOF = 0;
  public static final int EQUAL = 44;
  public static final int RBRACKET = 8;
  public static final int TRUE = 54;
  public static final int SIZE = 16;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int MOD = 33;
  public static final int PAIR = 12;
  public static final int IS_PAIR = 11;
  public static final int EQV = 17;
  public static final int COLON = 2;
  public static final int ELSE = 48;
  public static final int LBRACE = 5;
  public static final int READ = 26;
  public static final int LIST = 15;
  public static final int EQL = 18;
  public static final int SUBSTR = 19;
  public static final int LET = 28;
  public static final int THEN = 47;
  public static final int RBRACE = 6;
  public static final int LB_COLON = 9;
  public static final int STRING = 49;
  public static final int PROC = 21;
  public static final int DEF = 20;
  public static final int AT = 41;
  public static final int BIT_OR = 38;
  public static final int FALSE = 55;
  public static final int VAR = 50;
  public static final int PRINT = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LB_COLON",
  "RB_COLON",
  "IS_PAIR",
  "PAIR",
  "CAR",
  "CDR",
  "LIST",
  "SIZE",
  "EQV",
  "EQL",
  "SUBSTR",
  "DEF",
  "PROC",
  "NIL",
  "CASE",
  "PRINT",
  "PRINTLN",
  "READ",
  "READINT",
  "LET",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "BIT_AND",
  "BIT_OR",
  "BIT_NOT",
  "SEMI",
  "AT",
  "COND",
  "ASSIGN",
  "EQUAL",
  "COMMA",
  "IF",
  "THEN",
  "ELSE",
  "STRING",
  "VAR",
  "INT",
  "DOUBLE",
  "CHAR",
  "TRUE",
  "FALSE"
  };
}

